= Hacking

== Get, install
Basic use of the package is just go get, or git clone; go install.  There are
no dependencies outside the standard library.

== Build
CI is currently on travis-ci.org.

The build runs go vet with a few exceptions for things I'm not a big fan of.

https://github.com/client9/misspell has been valuable.

Also I wrote https://github.com/soniakeys/vetc to validate that each source
file has copyright/license statement.

Then, it’s not in the ci script, but I wrote https://github.com/soniakeys/rcv
to put coverage stats in the readme.  Maybe it could be commit hook or
something but for now I’ll try just running it manually now and then.

Go fmt is not in the ci script, but I have at least one editor set up to run
it on save, so code should stay formatted pretty well.

== Plans
The primary to-do list is the issue tracker on Github.

== Direction, focus, features
The project started with no real goal or purpose, just as a place for some code
that might be useful.  Here are some elements that characterize the direction.

* The focus has been on algorithms on adjacency lists.  That is, adjacency list
  is the fundamental representation for most implemented algorithms.  There are
  many other interesting representations, many reasons to use them, but
  adjacency list is common in literature and practice.  It has been useful to
  focus on this data representation, at first anyway.

* The API is rather low level.

* Slices instead of maps.  Maps are pretty efficient, and the property of
  unique keys can be useful, But slices are still faster and more efficient,
  and the unique key property is not always needed or wanted.  The Adjacency
  list implementation of this library is all done in slices.  Slices are used
  in algorithms where possible, in preference to maps.  Maps are still used in
  some cases where uniqueness is needed.  (But also bits are used.)

* Interfaces not generally used.  Algorithms are implemented directly on
  concrete data types and not on interfaces describing the capabilities of
  the data types.

* Code generation is used to provide methods that work on both labeled and
  unlabeled graphs.  Code is written to labeled types, then transformations
  generate the unlabled equivalents.

* The focus has been on single threaded algorithms.  Again, there is much new
  and interesting work being done with concurrent, parallel, and distributed
  graph algorithms, and Go might be an ideal language to implement some of
  these algorithms.  But as a preliminary step, more traditional
  single-threaded algorithms are implemented.

* Algorithms selected for implementation are generally ones commonly appearing
  in beginning graph theory discussions and in general purpose graph libraries
  in other programming languages.
