= Hacking

Basic use of the package is just go get, or git clone; go install.  There are
no dependencies outside the standard library.

The primary to-do list is the issue tracker on Github.  I maintained a
journal on google drive for a while but at some point filed issues for all
remaining ideas in that document that still seemed relevant.  So currently
there is no other roadmap or planning document.

CI is currently on travis-ci.org.

Im not big on making go vet happy just for a badge but I really like the
example check that I believe appeared with go 1.6.  (I think it will be a
standard check with 1.7, so the test script will have to change then.)

https://github.com/client9/misspell has been valuable.

Also I wrote https://github.com/soniakeys/vetc to validate that each source
file has copyright/license statement.

Then, it’s not in the ci script, but I wrote https://github.com/soniakeys/rcv
to put coverage stats in the readme.  Maybe it could be commit hook or
something but for now I’ll try just running it manually now and then.

Go fmt is not in the ci script, but I have at least one editor set up to run
it on save, so code should stay formatted pretty well.
